services:
  php:
    build:
      context: .
    platform: linux/amd64
    ports:
      - "8081:80"
    volumes:
      - ./src/public:/var/www/html
    extra_hosts:
      - "localhost:127.0.0.1"

  mysql:
    image: mysql:8.0
    container_name: mysql-php-app
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: userdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password

volumes:
  db_data:
